[font]
size = 11

[font.bold]
family = "Hasklug Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hasklug Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hasklug Nerd Font"
style = "Italic"

[font.normal]
family = "Hasklug Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
